//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickOnIndia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_ClickOnIndiaEntities : DbContext
    {
        public Db_ClickOnIndiaEntities()
            : base("name=Db_ClickOnIndiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Bus> tbl_Bus { get; set; }
        public virtual DbSet<tbl_BusBoking> tbl_BusBoking { get; set; }
        public virtual DbSet<tbl_BusLoc> tbl_BusLoc { get; set; }
        public virtual DbSet<tbl_BusRoute> tbl_BusRoute { get; set; }
        public virtual DbSet<tbl_Compartment> tbl_Compartment { get; set; }
        public virtual DbSet<tbl_HotelBooking> tbl_HotelBooking { get; set; }
        public virtual DbSet<tbl_HotelRoom> tbl_HotelRoom { get; set; }
        public virtual DbSet<tbl_Hotels> tbl_Hotels { get; set; }
        public virtual DbSet<tbl_Passenger> tbl_Passenger { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_RoomTypes> tbl_RoomTypes { get; set; }
        public virtual DbSet<tbl_Route> tbl_Route { get; set; }
        public virtual DbSet<tbl_SeatClass> tbl_SeatClass { get; set; }
        public virtual DbSet<tbl_Train> tbl_Train { get; set; }
        public virtual DbSet<tbl_TrainBooking> tbl_TrainBooking { get; set; }
        public virtual DbSet<tbl_TrainRoute> tbl_TrainRoute { get; set; }
        public virtual DbSet<tbl_Transaction> tbl_Transaction { get; set; }
        public virtual DbSet<tbl_UserDetail> tbl_UserDetail { get; set; }
    }
}
