//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickOnIndia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Train
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Train()
        {
            this.tbl_TrainRoute = new HashSet<tbl_TrainRoute>();
        }
    
        public int Tid { get; set; }
        public string TrainName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public string TrainNum { get; set; }
        public Nullable<int> Uid { get; set; }
    
        public virtual tbl_UserDetail tbl_UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrainRoute> tbl_TrainRoute { get; set; }
    }
}
