//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickOnIndia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Compartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Compartment()
        {
            this.tbl_SeatClass = new HashSet<tbl_SeatClass>();
        }
    
        public int Compid { get; set; }
        public string CompName { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Tid { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Uid { get; set; }
    
        public virtual tbl_UserDetail tbl_UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SeatClass> tbl_SeatClass { get; set; }
        public virtual tbl_Train tbl_Train { get; set; }
    }
}
