//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickOnIndia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BusLoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BusLoc()
        {
            this.tbl_BusRoute = new HashSet<tbl_BusRoute>();
        }
    
        public int Blid { get; set; }
        public string LocationXY { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Uid { get; set; }
        public string LocationName { get; set; }
    
        public virtual tbl_UserDetail tbl_UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BusRoute> tbl_BusRoute { get; set; }
    }
}
