//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickOnIndia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HotelBooking
    {
        public int Hbid { get; set; }
        public Nullable<int> Hid { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<int> Transid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Uid { get; set; }
    
        public virtual tbl_HotelRoom tbl_HotelRoom { get; set; }
        public virtual tbl_Hotels tbl_Hotels { get; set; }
        public virtual tbl_Transaction tbl_Transaction { get; set; }
        public virtual tbl_UserDetail tbl_UserDetail { get; set; }
    }
}
