//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickOnIndia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HotelRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_HotelRoom()
        {
            this.tbl_HotelBooking = new HashSet<tbl_HotelBooking>();
        }
    
        public int HotelRoomId { get; set; }
        public Nullable<int> Hid { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Uid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HotelBooking> tbl_HotelBooking { get; set; }
        public virtual tbl_Hotels tbl_Hotels { get; set; }
        public virtual tbl_RoomTypes tbl_RoomTypes { get; set; }
    }
}
